version: "3.3"
services:
  db:
    image: "mysql:8"
    environment:
      - "MYSQL_ROOT_PASSWORD=squad00"
      - "MYSQL_DATABASE=squad"
      - "MYSQL_USER=squad"
      - "MYSQL_PASSWORD=squad00"
    volumes: 
      - "${PWD}/db/mysql.conf.d:/etc/mysql/conf.d/"
      - "data-volume:/var/lib/mysql"
      - "${PWD}/db/scripts:/docker-entrypoint-initdb.d"
    ports:
      - 3306:3306
  squad-backend:
    build: "."
    links:
      - db:db
    environment:
      - "DB_HOST=db"
      - "DB_PORT=3306"
      - "DB_USER=squad"
      - "DB_PASSWORD=squad00"
    ports:
      - 8080:8080
volumes:
  data-volume: